### ISSUE TITLE
Bug with importing save file

### ISSUE THREAD

**Issue by xman2l** [GeopJr/DrKahls-Time-Machine#1]
I tried to use the Time machine to edit my save file but when i imported the file it gave me an error saying **[Error] TypeError: obj.isPlayer1Mugman is undefined** i tried to get other savefiles but it didnt work. thats all i can tell.

**Comment by xman2l** [comment]
![obrazek](https://user-images.githubusercontent.com/100595244/156006007-dc7bf145-0cf5-4618-8c14-442144b07560.png)

**Comment by GeopJr** [comment]
Thanks for raising this issue!

Unfortunately, this project is pretty abandoned (last meaningful update was **3** years ago). I haven't been up with Cuphead and its updates.

From the looks of it, `isPlayer1Mugman` is missing from your save file(?), which means that it might be older (or a new update removed it(?)).

Closing.
